baseURL = "/"
languageCode = "en-us"
title = "Chinese Developer Ecosystem Observer - Tech Insights"
theme = "PaperMod"

[params]
description = "Insights into China Software Industry and Developer Ecosystem"